# Apply special_abilities.json lvlunlock fixes from the 2 class audit reports.
# - Auto-applies WRONG entries with numeric canonical (just changes lvlunlock).
# - Does NOT delete entries, rename name_en, or touch descriptions.
# - Writes _audit/manual-review.md with everything that needs a human eye.
# Pure-ASCII source so PS 5.1 (no BOM) reads it correctly.

$ErrorActionPreference = 'Stop'
$base = 'C:\Users\Lucia\Documents\otros\pathfinder-sheet'
$saPath = "$base\special_abilities.json"
$reports = @(
    "$base\_audit\class-report-1.md",
    "$base\_audit\class-report-2.md"
)
$manualReview = "$base\_audit\manual-review.md"

# patches[entry_id] = canonical lvlunlock
$patches = @{}
$manualLines = New-Object System.Collections.ArrayList
[void]$manualLines.Add('# Manual review - class audit follow-ups')
[void]$manualLines.Add('')
[void]$manualLines.Add('Generated by _audit/apply-class-fixes.ps1. Lists items NOT auto-applied because they need human judgement (deletions, name swaps, homebrew without canon).')
[void]$manualLines.Add('')
[void]$manualLines.Add('## UNKNOWN entries (level not determinable)')
[void]$manualLines.Add('')
$unknownCount = 0
$wrongCount = 0
$okCount = 0
$bonusCount = 0
$nonNumericCanonical = New-Object System.Collections.ArrayList

# Capture: id, feature-name, current lvlunlock, canonical-raw, verdict, rest
$lineRx = '^-\s+([A-Za-z0-9_]+)\s+\|\s+"([^"]*)"[^|]*\|\s+lvlunlock:\s+(\d+)\s+\|\s+canonical:\s+([^|]+?)\s+\|\s+([A-Z]+)\s*\|(.*)$'

foreach ($rep in $reports) {
    $inBonus = $false
    $repText = [System.IO.File]::ReadAllText($rep, (New-Object System.Text.UTF8Encoding($false)))
    $repText -split "`r?`n" | ForEach-Object {
        $line = $_
        if ($line -match '^##\s+Bonus archetype findings') { $inBonus = $true; return }
        if ($line -match '^##\s+Summary')                  { $inBonus = $false; return }

        if ($line -match $lineRx) {
            $entryId = $matches[1]
            $featName = $matches[2]
            $current = [int]$matches[3]
            $canonicalRaw = $matches[4].Trim()
            $verdict = $matches[5].ToUpper()
            $rest = $matches[6].Trim()

            switch ($verdict) {
                'OK'      { $script:okCount++ }
                'UNKNOWN' {
                    $script:unknownCount++
                    [void]$manualLines.Add("- ``$entryId`` -- ""$featName"" (lvlunlock: $current) -- $rest")
                }
                'WRONG'   {
                    if ($canonicalRaw -match '^(\d+)') {
                        $canonical = [int]$matches[1]
                        if ($inBonus) { $script:bonusCount++ }
                        $patches[$entryId] = $canonical
                        $script:wrongCount++
                    } else {
                        [void]$nonNumericCanonical.Add("$entryId :: $featName :: current=$current :: canonical=$canonicalRaw :: $rest")
                    }
                }
            }
        }
    }
}

[void]$manualLines.Add('')
[void]$manualLines.Add('## WRONG entries with non-numeric canonical (delete / rename / split)')
[void]$manualLines.Add('')
$nonNumericCanonical | ForEach-Object { [void]$manualLines.Add("- $_") }

# Bonus archetype findings whose format the regex cannot match:
# either "bard | entry_id (archetype: ak)" lead, or "canonical: ~N" without an
# explicit VERDICT pipe. All values cross-checked against PF1e canon.
$bonusFixes = @{
    'archaeologist_archaeologists_luck'    = 1   # report 1: 19 -> 1 (lvl1 core archetype feature)
    'monster_tactician_summon_monster'     = 1   # report 1: 17 -> 1
    'exorcist_closed_mind'                 = 2   # report 1: 17 -> 2
    'order_of_the_flame_daunting_success'  = 8   # report 2: ~8
    'order_of_the_flame_foolhardy_rush'    = 2   # report 2: ~2
    'order_of_the_flame_blaze_of_glory'    = 15  # report 2: ~15
    'order_of_the_flame_glorious_challenge'= 2   # report 2: ~2
    'kensai_critical_perfection'           = 9   # report 2: UM Kensai lvl 9
    'kensai_iaijutsu_master'               = 17  # report 2: UM Kensai lvl 17
}
foreach ($k in $bonusFixes.Keys) {
    if (-not $patches.ContainsKey($k)) { $patches[$k] = $bonusFixes[$k]; $wrongCount++ }
}

Write-Host "Parsed: WRONG=$wrongCount  UNKNOWN=$unknownCount  OK=$okCount  Bonus(in WRONG)=$bonusCount  NonNumericCanonical=$($nonNumericCanonical.Count)"
Write-Host "Unique entry_ids to patch: $($patches.Keys.Count)"
Write-Host ''

# Load special_abilities.json with strict UTF-8 (no BOM via .NET)
$saRaw = [System.IO.File]::ReadAllText($saPath, (New-Object System.Text.UTF8Encoding($false)))
$sa = $saRaw | ConvertFrom-Json
Write-Host "Loaded $($sa.Count) special_abilities entries"

# Build id index
$byId = @{}
foreach ($e in $sa) { if ($e.id) { $byId[$e.id] = $e } }

$applied = 0
$unmatched = New-Object System.Collections.ArrayList
$noChange = 0
foreach ($id in $patches.Keys) {
    $canonical = $patches[$id]
    $entry = $byId[$id]
    if (-not $entry) {
        [void]$unmatched.Add($id)
        continue
    }
    if ($entry.lvlunlock -ne $canonical) {
        $entry.lvlunlock = $canonical
        $applied++
    } else {
        $noChange++
    }
}

Write-Host "lvlunlock values updated: $applied"
Write-Host "Already at canonical (no-op): $noChange"
Write-Host "entry_ids in reports but missing from JSON: $($unmatched.Count)"
if ($unmatched.Count -gt 0) {
    $unmatched | ForEach-Object { Write-Host "  - $_" }
    [void]$manualLines.Add('')
    [void]$manualLines.Add('## entry_ids referenced by reports but not present in special_abilities.json')
    [void]$manualLines.Add('')
    $unmatched | ForEach-Object { [void]$manualLines.Add("- ``$_``") }
}

# Serialize back
$out = $sa | ConvertTo-Json -Depth 100
$out = $out -replace '\\u003c','<' -replace '\\u003e','>' -replace '\\u0026','&'

# Detect original BOM and match on write
$origFirst3 = New-Object byte[] 3
$fs = [System.IO.File]::OpenRead("$base\_audit\special_abilities.original.json")
[void]$fs.Read($origFirst3, 0, 3); $fs.Close()
$hasBom = ($origFirst3[0] -eq 0xEF -and $origFirst3[1] -eq 0xBB -and $origFirst3[2] -eq 0xBF)
[System.IO.File]::WriteAllText($saPath, $out, (New-Object System.Text.UTF8Encoding($hasBom)))
Write-Host "Wrote $saPath ($((Get-Item $saPath).Length) bytes, BOM=$hasBom)"

# Write manual-review.md
[System.IO.File]::WriteAllText($manualReview, ($manualLines -join "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $manualReview"
